### ISSUE TITLE
When installing I get:  `ember generate` command requires an entity name to be specified

### ISSUE THREAD

**Issue by QuantumInformation** [poetic/ember-cli-github-pages#16]
I just tried to install this on a 0.2.3 cli project
```
 ember install ember-cli-github-pages
```

but get this error/output to the console:

The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

Note:I've switched to mac now, not on windows:)

**Comment by QuantumInformation** [comment]
Also when I ran:
ember github-pages:commit --message "Initial gh-pages release"
I got this:
The specified command github-pages:commit is invalid. For available options, see `ember help`.

**Comment by alekspetrov** [comment]
I've got the same issue!

**Comment by QuantumInformation** [comment]
I tried on a different 0.2.5 project and have the same error again:

`The specified command github-pages:commit is invalid. For available options, see `ember help`.
`

**Comment by QuantumInformation** [comment]
Anyone know what the cause if this is? Is it a simplish fix?

**Comment by truenorth** [comment]
@QuantumInformation when you run
```
ember help
```
do you see something like this?
![screen shot 2015-06-06 at 2 07 06 pm](https://cloud.githubusercontent.com/assets/558005/8021466/6406aaac-0c55-11e5-8283-689be331a0df.png)

If not, I suggest
```
npm uninstall ember-cli-github-pages --save-dev
ember install ember-cli-github-pages@0.0.*
```

**Comment by jhr007** [comment]
> The specified command github-pages:commit is invalid. For available options, see ember help.

When I got this message it was because ember-cli didn't see the addon in the `package.json['devDependencies']` despite it existing in node_modules. Probably an `npm install`  without `--save-dev` on my part, or the error below stopped npm from writing to package.json (not sure on this last part)

As truenorth said uninstall then ember install. Or manually add to package.json. 

The benefit of `ember install some-addon` is that it runs the default blueprint for that addon which usually includes some prep from the addon. 

> The ember generate command requires an entity name to be specified. For more details, use ember help.

Ember-cli's install command runs the addon's default blueprint. If the blueprint doesn't have an override for `normalizeEntityName`, ember-cli is expecting a name, but `ember install` doesn't provide one. Think `ember generate controller some-name` but some-name is never passed by `ember install`.
