### ISSUE TITLE
--environment is not a valid option

### ISSUE THREAD

**Issue by erichonkanen** [poetic/ember-cli-github-pages#28]
new to this and when I tried to use `--environment=production`, I got error saying `--environment` is not a valid option (`--message` was the only one listed)

**Comment by truenorth** [comment]
can you look in your node_modules folder and verify that you're using `v0.0.6`? This flag was recently added

**Comment by erichonkanen** [comment]
shoot i think it was 0.0.4.. thanks!

**Comment by erichonkanen** [comment]
actually while I have your attention.. I tried for a few hours to get it working and ended up bailing out and just threw a heroku app together (it was for a demo for oss project)...

the issue was I could not get the proj/tests/dummy/config/environment.js file to load.. was there anything special i was supposed to do for that?

**Comment by erichonkanen** [comment]
it was for a PR for the main repo https://github.com/erichonkanen/ember-cli-simple-auth-token/blob/master/tests/dummy/config/environment.js

**Comment by truenorth** [comment]
I suspect that your environment.js file is loading. Without it, your app would have major issues.

I added The `--environment` flag because, for an addon demo page, there's some value to running in "development" (i.e., if you have Pretender simulating API responses like the demo pages of [hhff/ember-infinity](https://github.com/hhff/ember-infinity) and [truenorth/ember-api-actions](https://github.com/truenorth/ember-api-actions) and [pretender is not enabled in production](https://github.com/rwjblue/ember-cli-pretender/blob/master/index.js#L13-L21)). 

Let me take a look at the demo page for that addon and see what I can do .

**Comment by truenorth** [comment]
that looks totally reasonable to me. If you get snagged again ping me and I'll take a look.
